export const tmpData = [
  {
    videoId: "1",
    title: "제목입니다아앙앙",
    thumbnail: "https:",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
  {
    videoId: "2",
    title: "제목입니다아앙앙",
    thumbnail: "https:",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
  {
    videoId: "3",
    title: "제목입니다아앙앙",
    thumbnail: "https:",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
];
