export const tmpData = [
  {
    videoId: "1",
    title:
      "너 나랑 자려고 계속 만나는 거 모를 줄 알아? [연애의 참견] EP.188 | KBS Joy 230815 방송",
    thumbnail:
      "https://i.ytimg.com/vi/j4HbqwZN2CE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCwO3WATeQ7grZDQN4b7dXV-DF1HQ",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
  {
    videoId: "2",
    title: "제목입니다아앙앙",
    thumbnail: "https:",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
  {
    videoId: "3",
    title: "제목입니다아앙앙",
    thumbnail: "https:",
    percent: "12.323232",
    top5_text: ["dfsadfs"],
    low5_text: ["dfasdfas"],
    keyword: ["아이유", "안라낭ㄹ나"],
    likes: 58,
    likes_text: ["Sdfasdf"],
    relation_thumbnails: ["hhh"],
    relation_title: ["tht"],
    relation_id: ["dfasdf"],
    time: [["22/04", 4]],
  },
];
