import { DataContextProvider } from "@/contexts/analysisData";
import "../styles/globals.scss";
import { ErrorBoundary } from "react-error-boundary";
import Error from "./error";

export const metadata = {
  title: "TubeAna",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary FallbackComponent={Error}>
          <DataContextProvider>{children}</DataContextProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
