import { DataContextProvider } from "@/contexts/analysisData";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DataContextProvider>{children}</DataContextProvider>
      </body>
    </html>
  );
}
